#!/usr/bin/env bash

# Local one-command wrapper. Compilation runs in the official S100/TROS Docker
# image; host aarch64 compilers are intentionally not used.

set -Eeuo pipefail

readonly SOURCE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
readonly IMAGE="${S100_IMAGE:-pc_tros_ubuntu22.04:v1.0.0}"
readonly IMAGE_URL="${S100_IMAGE_URL:-http://archive.d-robotics.cc/TogetheROS/cross_compile_docker/pc_tros_ubuntu22.04_v1.0.0.tar.gz}"
readonly IMAGE_SHA256="${S100_IMAGE_SHA256:-ec065c268782373311421f0bb7f2212bfec6584a7070a9737468055a6bce2c88}"
readonly CACHE_ROOT="${S100_CACHE_ROOT:-/data/stereohobot-s100-cache}"
readonly WORK_ROOT="${S100_WORK_ROOT:-/data/stereohobot-s100-local}"
readonly IMAGE_ARCHIVE="${S100_IMAGE_ARCHIVE:-${CACHE_ROOT}/images/pc_tros_ubuntu22.04_v1.0.0.tar.gz}"

if ! docker image inspect "${IMAGE}" >/dev/null 2>&1; then
  mkdir -p "$(dirname "${IMAGE_ARCHIVE}")"
  if [[ ! -f "${IMAGE_ARCHIVE}" ]]; then
    echo "Downloading official TROS S100 toolchain image..."
    curl --fail --location --retry 5 --retry-all-errors --continue-at - \
      --output "${IMAGE_ARCHIVE}" "${IMAGE_URL}"
  fi
  echo "${IMAGE_SHA256}  ${IMAGE_ARCHIVE}" | sha256sum --check
  docker load --input "${IMAGE_ARCHIVE}"
fi

# Automatically reuse the validated cache generated by the reference omni_slam
# S100 workflow when it is available on this development machine.
if [[ -z "${S100_CACHE_ROOT+x}" && \
      -d /data/omni-s100-local/workspace/cache/sysroot_docker-de9fa286f71a72d24c349477cd59f41cc2cc3d8f/usr_s100 ]]; then
  export S100_CACHE_ROOT=/data/omni-s100-local/workspace/cache
else
  export S100_CACHE_ROOT="${CACHE_ROOT}"
fi
if [[ -z "${S100_ROBOT_DEV_CONFIG_SOURCE:-}" && \
      -f /data/omni-s100-local/workspace/cc_ws/tros_ws/robot_dev_config/aarch64_toolchainfile.cmake ]]; then
  export S100_ROBOT_DEV_CONFIG_SOURCE=/data/omni-s100-local/workspace/cc_ws/tros_ws/robot_dev_config
fi

export S100_SOURCE_ROOT="${SOURCE_ROOT}"
export S100_WORK_ROOT="${WORK_ROOT}"
export S100_IMAGE="${IMAGE}"

exec "${SOURCE_ROOT}/ci/build_ros2_s100_cross.sh"
